// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: gRPC/service.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sex int32

const (
	Sex_SEX_UNSPECIFIED Sex = 0
	Sex_SEX_MALE        Sex = 1
	Sex_SEX_FEMALE      Sex = 2
)

// Enum value maps for Sex.
var (
	Sex_name = map[int32]string{
		0: "SEX_UNSPECIFIED",
		1: "SEX_MALE",
		2: "SEX_FEMALE",
	}
	Sex_value = map[string]int32{
		"SEX_UNSPECIFIED": 0,
		"SEX_MALE":        1,
		"SEX_FEMALE":      2,
	}
)

func (x Sex) Enum() *Sex {
	p := new(Sex)
	*p = x
	return p
}

func (x Sex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sex) Descriptor() protoreflect.EnumDescriptor {
	return file_gRPC_service_proto_enumTypes[0].Descriptor()
}

func (Sex) Type() protoreflect.EnumType {
	return &file_gRPC_service_proto_enumTypes[0]
}

func (x Sex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sex.Descriptor instead.
func (Sex) EnumDescriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{0}
}

type PhotoType int32

const (
	PhotoType_PHOTO_TYPE_UNSPECIFIED PhotoType = 0
	PhotoType_PHOTO_TYPE_PRIMARY     PhotoType = 1
	PhotoType_PHOTO_TYPE_EXTRA       PhotoType = 2
)

// Enum value maps for PhotoType.
var (
	PhotoType_name = map[int32]string{
		0: "PHOTO_TYPE_UNSPECIFIED",
		1: "PHOTO_TYPE_PRIMARY",
		2: "PHOTO_TYPE_EXTRA",
	}
	PhotoType_value = map[string]int32{
		"PHOTO_TYPE_UNSPECIFIED": 0,
		"PHOTO_TYPE_PRIMARY":     1,
		"PHOTO_TYPE_EXTRA":       2,
	}
)

func (x PhotoType) Enum() *PhotoType {
	p := new(PhotoType)
	*p = x
	return p
}

func (x PhotoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhotoType) Descriptor() protoreflect.EnumDescriptor {
	return file_gRPC_service_proto_enumTypes[1].Descriptor()
}

func (PhotoType) Type() protoreflect.EnumType {
	return &file_gRPC_service_proto_enumTypes[1]
}

func (x PhotoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhotoType.Descriptor instead.
func (PhotoType) EnumDescriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{1}
}

type City struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *City) Reset() {
	*x = City{}
	mi := &file_gRPC_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{0}
}

func (x *City) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserPhoto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"` // 1..6 (only additional photos).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPhoto) Reset() {
	*x = UserPhoto{}
	mi := &file_gRPC_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPhoto) ProtoMessage() {}

func (x *UserPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPhoto.ProtoReflect.Descriptor instead.
func (*UserPhoto) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserPhoto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserPhoto) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *UserPhoto) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UserPhoto) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type User struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUIDv7
	FirstName             string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName              string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                 string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	BirthDate             string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"` // RFC3339 date-only format (YYYY-MM-DD).
	Bio                   string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	ToilerScore           int32                  `protobuf:"varint,7,opt,name=toiler_score,json=toilerScore,proto3" json:"toiler_score,omitempty"` // 1..10
	AlcoholInfo           string                 `protobuf:"bytes,8,opt,name=alcohol_info,json=alcoholInfo,proto3" json:"alcohol_info,omitempty"`
	SmokingInfo           string                 `protobuf:"bytes,9,opt,name=smoking_info,json=smokingInfo,proto3" json:"smoking_info,omitempty"`
	Sex                   Sex                    `protobuf:"varint,10,opt,name=sex,proto3,enum=user.v1.Sex" json:"sex,omitempty"`
	HeightCm              int32                  `protobuf:"varint,11,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	City                  *City                  `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	PrimaryPhotoObjectKey string                 `protobuf:"bytes,13,opt,name=primary_photo_object_key,json=primaryPhotoObjectKey,proto3" json:"primary_photo_object_key,omitempty"`
	PrimaryPhotoUrl       string                 `protobuf:"bytes,14,opt,name=primary_photo_url,json=primaryPhotoUrl,proto3" json:"primary_photo_url,omitempty"`
	ExtraPhotos           []*UserPhoto           `protobuf:"bytes,15,rep,name=extra_photos,json=extraPhotos,proto3" json:"extra_photos,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gRPC_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetToilerScore() int32 {
	if x != nil {
		return x.ToilerScore
	}
	return 0
}

func (x *User) GetAlcoholInfo() string {
	if x != nil {
		return x.AlcoholInfo
	}
	return ""
}

func (x *User) GetSmokingInfo() string {
	if x != nil {
		return x.SmokingInfo
	}
	return ""
}

func (x *User) GetSex() Sex {
	if x != nil {
		return x.Sex
	}
	return Sex_SEX_UNSPECIFIED
}

func (x *User) GetHeightCm() int32 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *User) GetCity() *City {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *User) GetPrimaryPhotoObjectKey() string {
	if x != nil {
		return x.PrimaryPhotoObjectKey
	}
	return ""
}

func (x *User) GetPrimaryPhotoUrl() string {
	if x != nil {
		return x.PrimaryPhotoUrl
	}
	return ""
}

func (x *User) GetExtraPhotos() []*UserPhoto {
	if x != nil {
		return x.ExtraPhotos
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FirstName             string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName              string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                 string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	BirthDate             string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"` // YYYY-MM-DD
	Bio                   string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	ToilerScore           int32                  `protobuf:"varint,6,opt,name=toiler_score,json=toilerScore,proto3" json:"toiler_score,omitempty"`
	AlcoholInfo           string                 `protobuf:"bytes,7,opt,name=alcohol_info,json=alcoholInfo,proto3" json:"alcohol_info,omitempty"`
	SmokingInfo           string                 `protobuf:"bytes,8,opt,name=smoking_info,json=smokingInfo,proto3" json:"smoking_info,omitempty"`
	Sex                   Sex                    `protobuf:"varint,9,opt,name=sex,proto3,enum=user.v1.Sex" json:"sex,omitempty"`
	HeightCm              int32                  `protobuf:"varint,10,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	CityId                int64                  `protobuf:"varint,11,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	PrimaryPhotoObjectKey string                 `protobuf:"bytes,12,opt,name=primary_photo_object_key,json=primaryPhotoObjectKey,proto3" json:"primary_photo_object_key,omitempty"`
	PrimaryPhotoUrl       string                 `protobuf:"bytes,13,opt,name=primary_photo_url,json=primaryPhotoUrl,proto3" json:"primary_photo_url,omitempty"`
	ExtraPhotos           []*NewUserPhoto        `protobuf:"bytes,14,rep,name=extra_photos,json=extraPhotos,proto3" json:"extra_photos,omitempty"` // max 6
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_gRPC_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CreateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateUserRequest) GetToilerScore() int32 {
	if x != nil {
		return x.ToilerScore
	}
	return 0
}

func (x *CreateUserRequest) GetAlcoholInfo() string {
	if x != nil {
		return x.AlcoholInfo
	}
	return ""
}

func (x *CreateUserRequest) GetSmokingInfo() string {
	if x != nil {
		return x.SmokingInfo
	}
	return ""
}

func (x *CreateUserRequest) GetSex() Sex {
	if x != nil {
		return x.Sex
	}
	return Sex_SEX_UNSPECIFIED
}

func (x *CreateUserRequest) GetHeightCm() int32 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *CreateUserRequest) GetCityId() int64 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *CreateUserRequest) GetPrimaryPhotoObjectKey() string {
	if x != nil {
		return x.PrimaryPhotoObjectKey
	}
	return ""
}

func (x *CreateUserRequest) GetPrimaryPhotoUrl() string {
	if x != nil {
		return x.PrimaryPhotoUrl
	}
	return ""
}

func (x *CreateUserRequest) GetExtraPhotos() []*NewUserPhoto {
	if x != nil {
		return x.ExtraPhotos
	}
	return nil
}

type NewUserPhoto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"` // 1..6
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUserPhoto) Reset() {
	*x = NewUserPhoto{}
	mi := &file_gRPC_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUserPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserPhoto) ProtoMessage() {}

func (x *NewUserPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserPhoto.ProtoReflect.Descriptor instead.
func (*NewUserPhoto) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{4}
}

func (x *NewUserPhoto) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *NewUserPhoto) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NewUserPhoto) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_gRPC_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUIDv7
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_gRPC_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_gRPC_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUIDv7
	FirstName             *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName              *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Email                 *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	BirthDate             *string                `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3,oneof" json:"birth_date,omitempty"`
	Bio                   *string                `protobuf:"bytes,6,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	ToilerScore           *int32                 `protobuf:"varint,7,opt,name=toiler_score,json=toilerScore,proto3,oneof" json:"toiler_score,omitempty"`
	AlcoholInfo           *string                `protobuf:"bytes,8,opt,name=alcohol_info,json=alcoholInfo,proto3,oneof" json:"alcohol_info,omitempty"`
	SmokingInfo           *string                `protobuf:"bytes,9,opt,name=smoking_info,json=smokingInfo,proto3,oneof" json:"smoking_info,omitempty"`
	Sex                   *Sex                   `protobuf:"varint,10,opt,name=sex,proto3,enum=user.v1.Sex,oneof" json:"sex,omitempty"`
	HeightCm              *int32                 `protobuf:"varint,11,opt,name=height_cm,json=heightCm,proto3,oneof" json:"height_cm,omitempty"`
	CityId                *int64                 `protobuf:"varint,12,opt,name=city_id,json=cityId,proto3,oneof" json:"city_id,omitempty"`
	PrimaryPhotoObjectKey *string                `protobuf:"bytes,13,opt,name=primary_photo_object_key,json=primaryPhotoObjectKey,proto3,oneof" json:"primary_photo_object_key,omitempty"`
	PrimaryPhotoUrl       *string                `protobuf:"bytes,14,opt,name=primary_photo_url,json=primaryPhotoUrl,proto3,oneof" json:"primary_photo_url,omitempty"`
	ExtraPhotos           []*NewUserPhoto        `protobuf:"bytes,15,rep,name=extra_photos,json=extraPhotos,proto3" json:"extra_photos,omitempty"` // Replace additional photos list.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_gRPC_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetBirthDate() string {
	if x != nil && x.BirthDate != nil {
		return *x.BirthDate
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateUserRequest) GetToilerScore() int32 {
	if x != nil && x.ToilerScore != nil {
		return *x.ToilerScore
	}
	return 0
}

func (x *UpdateUserRequest) GetAlcoholInfo() string {
	if x != nil && x.AlcoholInfo != nil {
		return *x.AlcoholInfo
	}
	return ""
}

func (x *UpdateUserRequest) GetSmokingInfo() string {
	if x != nil && x.SmokingInfo != nil {
		return *x.SmokingInfo
	}
	return ""
}

func (x *UpdateUserRequest) GetSex() Sex {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return Sex_SEX_UNSPECIFIED
}

func (x *UpdateUserRequest) GetHeightCm() int32 {
	if x != nil && x.HeightCm != nil {
		return *x.HeightCm
	}
	return 0
}

func (x *UpdateUserRequest) GetCityId() int64 {
	if x != nil && x.CityId != nil {
		return *x.CityId
	}
	return 0
}

func (x *UpdateUserRequest) GetPrimaryPhotoObjectKey() string {
	if x != nil && x.PrimaryPhotoObjectKey != nil {
		return *x.PrimaryPhotoObjectKey
	}
	return ""
}

func (x *UpdateUserRequest) GetPrimaryPhotoUrl() string {
	if x != nil && x.PrimaryPhotoUrl != nil {
		return *x.PrimaryPhotoUrl
	}
	return ""
}

func (x *UpdateUserRequest) GetExtraPhotos() []*NewUserPhoto {
	if x != nil {
		return x.ExtraPhotos
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_gRPC_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUIDv7
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_gRPC_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_gRPC_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{11}
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // default 20
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	CityId        int64                  `protobuf:"varint,3,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"` // optional, if 0 - no filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_gRPC_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUsersRequest) GetCityId() int64 {
	if x != nil {
		return x.CityId
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_gRPC_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserPhotoUploadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUIDv7
	PhotoType     PhotoType              `protobuf:"varint,2,opt,name=photo_type,json=photoType,proto3,enum=user.v1.PhotoType" json:"photo_type,omitempty"`
	ExtraPosition int32                  `protobuf:"varint,3,opt,name=extra_position,json=extraPosition,proto3" json:"extra_position,omitempty"` // required for PHOTO_TYPE_EXTRA, valid: 1..6
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`        // image/jpeg, image/png, image/webp
	ContentLength int64                  `protobuf:"varint,5,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"` // bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPhotoUploadUrlRequest) Reset() {
	*x = GetUserPhotoUploadUrlRequest{}
	mi := &file_gRPC_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPhotoUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPhotoUploadUrlRequest) ProtoMessage() {}

func (x *GetUserPhotoUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPhotoUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUserPhotoUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserPhotoUploadUrlRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPhotoUploadUrlRequest) GetPhotoType() PhotoType {
	if x != nil {
		return x.PhotoType
	}
	return PhotoType_PHOTO_TYPE_UNSPECIFIED
}

func (x *GetUserPhotoUploadUrlRequest) GetExtraPosition() int32 {
	if x != nil {
		return x.ExtraPosition
	}
	return 0
}

func (x *GetUserPhotoUploadUrlRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetUserPhotoUploadUrlRequest) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type GetUserPhotoUploadUrlResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey        string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	UploadUrl        string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserPhotoUploadUrlResponse) Reset() {
	*x = GetUserPhotoUploadUrlResponse{}
	mi := &file_gRPC_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPhotoUploadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPhotoUploadUrlResponse) ProtoMessage() {}

func (x *GetUserPhotoUploadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPhotoUploadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUserPhotoUploadUrlResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserPhotoUploadUrlResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *GetUserPhotoUploadUrlResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUserPhotoUploadUrlResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type ConfirmUserPhotoUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUIDv7
	PhotoType     PhotoType              `protobuf:"varint,2,opt,name=photo_type,json=photoType,proto3,enum=user.v1.PhotoType" json:"photo_type,omitempty"`
	ExtraPosition int32                  `protobuf:"varint,3,opt,name=extra_position,json=extraPosition,proto3" json:"extra_position,omitempty"` // required for PHOTO_TYPE_EXTRA
	ObjectKey     string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUserPhotoUploadRequest) Reset() {
	*x = ConfirmUserPhotoUploadRequest{}
	mi := &file_gRPC_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUserPhotoUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUserPhotoUploadRequest) ProtoMessage() {}

func (x *ConfirmUserPhotoUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUserPhotoUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUserPhotoUploadRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{16}
}

func (x *ConfirmUserPhotoUploadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmUserPhotoUploadRequest) GetPhotoType() PhotoType {
	if x != nil {
		return x.PhotoType
	}
	return PhotoType_PHOTO_TYPE_UNSPECIFIED
}

func (x *ConfirmUserPhotoUploadRequest) GetExtraPosition() int32 {
	if x != nil {
		return x.ExtraPosition
	}
	return 0
}

func (x *ConfirmUserPhotoUploadRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type ConfirmUserPhotoUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUserPhotoUploadResponse) Reset() {
	*x = ConfirmUserPhotoUploadResponse{}
	mi := &file_gRPC_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUserPhotoUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUserPhotoUploadResponse) ProtoMessage() {}

func (x *ConfirmUserPhotoUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUserPhotoUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUserPhotoUploadResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{17}
}

func (x *ConfirmUserPhotoUploadResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`     // UUIDv7
	PhotoId       int64                  `protobuf:"varint,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"` // id from user_photos table (only extra photo)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserPhotoRequest) Reset() {
	*x = DeleteUserPhotoRequest{}
	mi := &file_gRPC_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPhotoRequest) ProtoMessage() {}

func (x *DeleteUserPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPhotoRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserPhotoRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteUserPhotoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserPhotoRequest) GetPhotoId() int64 {
	if x != nil {
		return x.PhotoId
	}
	return 0
}

type DeleteUserPhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserPhotoResponse) Reset() {
	*x = DeleteUserPhotoResponse{}
	mi := &file_gRPC_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPhotoResponse) ProtoMessage() {}

func (x *DeleteUserPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPhotoResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserPhotoResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{19}
}

type GetUserPhotoDownloadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUIDv7
	PhotoType     PhotoType              `protobuf:"varint,2,opt,name=photo_type,json=photoType,proto3,enum=user.v1.PhotoType" json:"photo_type,omitempty"`
	PhotoId       int64                  `protobuf:"varint,3,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"` // required for PHOTO_TYPE_EXTRA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPhotoDownloadUrlRequest) Reset() {
	*x = GetUserPhotoDownloadUrlRequest{}
	mi := &file_gRPC_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPhotoDownloadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPhotoDownloadUrlRequest) ProtoMessage() {}

func (x *GetUserPhotoDownloadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPhotoDownloadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUserPhotoDownloadUrlRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserPhotoDownloadUrlRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPhotoDownloadUrlRequest) GetPhotoType() PhotoType {
	if x != nil {
		return x.PhotoType
	}
	return PhotoType_PHOTO_TYPE_UNSPECIFIED
}

func (x *GetUserPhotoDownloadUrlRequest) GetPhotoId() int64 {
	if x != nil {
		return x.PhotoId
	}
	return 0
}

type GetUserPhotoDownloadUrlResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl      string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserPhotoDownloadUrlResponse) Reset() {
	*x = GetUserPhotoDownloadUrlResponse{}
	mi := &file_gRPC_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPhotoDownloadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPhotoDownloadUrlResponse) ProtoMessage() {}

func (x *GetUserPhotoDownloadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPhotoDownloadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUserPhotoDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserPhotoDownloadUrlResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GetUserPhotoDownloadUrlResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

var File_gRPC_service_proto protoreflect.FileDescriptor

const file_gRPC_service_proto_rawDesc = "" +
	"\n" +
	"\x12gRPC/service.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x04City\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"h\n" +
	"\tUserPhoto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"\xf4\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tR\tbirthDate\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12!\n" +
	"\ftoiler_score\x18\a \x01(\x05R\vtoilerScore\x12!\n" +
	"\falcohol_info\x18\b \x01(\tR\valcoholInfo\x12!\n" +
	"\fsmoking_info\x18\t \x01(\tR\vsmokingInfo\x12\x1e\n" +
	"\x03sex\x18\n" +
	" \x01(\x0e2\f.user.v1.SexR\x03sex\x12\x1b\n" +
	"\theight_cm\x18\v \x01(\x05R\bheightCm\x12!\n" +
	"\x04city\x18\f \x01(\v2\r.user.v1.CityR\x04city\x127\n" +
	"\x18primary_photo_object_key\x18\r \x01(\tR\x15primaryPhotoObjectKey\x12*\n" +
	"\x11primary_photo_url\x18\x0e \x01(\tR\x0fprimaryPhotoUrl\x125\n" +
	"\fextra_photos\x18\x0f \x03(\v2\x12.user.v1.UserPhotoR\vextraPhotos\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf4\x03\n" +
	"\x11CreateUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tR\tbirthDate\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12!\n" +
	"\ftoiler_score\x18\x06 \x01(\x05R\vtoilerScore\x12!\n" +
	"\falcohol_info\x18\a \x01(\tR\valcoholInfo\x12!\n" +
	"\fsmoking_info\x18\b \x01(\tR\vsmokingInfo\x12\x1e\n" +
	"\x03sex\x18\t \x01(\x0e2\f.user.v1.SexR\x03sex\x12\x1b\n" +
	"\theight_cm\x18\n" +
	" \x01(\x05R\bheightCm\x12\x17\n" +
	"\acity_id\x18\v \x01(\x03R\x06cityId\x127\n" +
	"\x18primary_photo_object_key\x18\f \x01(\tR\x15primaryPhotoObjectKey\x12*\n" +
	"\x11primary_photo_url\x18\r \x01(\tR\x0fprimaryPhotoUrl\x128\n" +
	"\fextra_photos\x18\x0e \x03(\v2\x15.user.v1.NewUserPhotoR\vextraPhotos\"[\n" +
	"\fNewUserPhoto\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"7\n" +
	"\x12CreateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x0fGetUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"\x94\x06\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x02R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tH\x03R\tbirthDate\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\x06 \x01(\tH\x04R\x03bio\x88\x01\x01\x12&\n" +
	"\ftoiler_score\x18\a \x01(\x05H\x05R\vtoilerScore\x88\x01\x01\x12&\n" +
	"\falcohol_info\x18\b \x01(\tH\x06R\valcoholInfo\x88\x01\x01\x12&\n" +
	"\fsmoking_info\x18\t \x01(\tH\aR\vsmokingInfo\x88\x01\x01\x12#\n" +
	"\x03sex\x18\n" +
	" \x01(\x0e2\f.user.v1.SexH\bR\x03sex\x88\x01\x01\x12 \n" +
	"\theight_cm\x18\v \x01(\x05H\tR\bheightCm\x88\x01\x01\x12\x1c\n" +
	"\acity_id\x18\f \x01(\x03H\n" +
	"R\x06cityId\x88\x01\x01\x12<\n" +
	"\x18primary_photo_object_key\x18\r \x01(\tH\vR\x15primaryPhotoObjectKey\x88\x01\x01\x12/\n" +
	"\x11primary_photo_url\x18\x0e \x01(\tH\fR\x0fprimaryPhotoUrl\x88\x01\x01\x128\n" +
	"\fextra_photos\x18\x0f \x03(\v2\x15.user.v1.NewUserPhotoR\vextraPhotosB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_emailB\r\n" +
	"\v_birth_dateB\x06\n" +
	"\x04_bioB\x0f\n" +
	"\r_toiler_scoreB\x0f\n" +
	"\r_alcohol_infoB\x0f\n" +
	"\r_smoking_infoB\x06\n" +
	"\x04_sexB\f\n" +
	"\n" +
	"_height_cmB\n" +
	"\n" +
	"\b_city_idB\x1b\n" +
	"\x19_primary_photo_object_keyB\x14\n" +
	"\x12_primary_photo_url\"7\n" +
	"\x12UpdateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x14\n" +
	"\x12DeleteUserResponse\"Y\n" +
	"\x10ListUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x17\n" +
	"\acity_id\x18\x03 \x01(\x03R\x06cityId\"8\n" +
	"\x11ListUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.user.v1.UserR\x05users\"\xdb\x01\n" +
	"\x1cGetUserPhotoUploadUrlRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\n" +
	"photo_type\x18\x02 \x01(\x0e2\x12.user.v1.PhotoTypeR\tphotoType\x12%\n" +
	"\x0eextra_position\x18\x03 \x01(\x05R\rextraPosition\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12%\n" +
	"\x0econtent_length\x18\x05 \x01(\x03R\rcontentLength\"\x8b\x01\n" +
	"\x1dGetUserPhotoUploadUrlResponse\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x03R\x10expiresInSeconds\"\xb1\x01\n" +
	"\x1dConfirmUserPhotoUploadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\n" +
	"photo_type\x18\x02 \x01(\x0e2\x12.user.v1.PhotoTypeR\tphotoType\x12%\n" +
	"\x0eextra_position\x18\x03 \x01(\x05R\rextraPosition\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\"C\n" +
	"\x1eConfirmUserPhotoUploadResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"L\n" +
	"\x16DeleteUserPhotoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bphoto_id\x18\x02 \x01(\x03R\aphotoId\"\x19\n" +
	"\x17DeleteUserPhotoResponse\"\x87\x01\n" +
	"\x1eGetUserPhotoDownloadUrlRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\n" +
	"photo_type\x18\x02 \x01(\x0e2\x12.user.v1.PhotoTypeR\tphotoType\x12\x19\n" +
	"\bphoto_id\x18\x03 \x01(\x03R\aphotoId\"r\n" +
	"\x1fGetUserPhotoDownloadUrlResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12,\n" +
	"\x12expires_in_seconds\x18\x02 \x01(\x03R\x10expiresInSeconds*8\n" +
	"\x03Sex\x12\x13\n" +
	"\x0fSEX_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSEX_MALE\x10\x01\x12\x0e\n" +
	"\n" +
	"SEX_FEMALE\x10\x02*U\n" +
	"\tPhotoType\x12\x1a\n" +
	"\x16PHOTO_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PHOTO_TYPE_PRIMARY\x10\x01\x12\x14\n" +
	"\x10PHOTO_TYPE_EXTRA\x10\x022\xfb\x05\n" +
	"\vUserService\x12E\n" +
	"\n" +
	"CreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponse\x12<\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponse\x12E\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x1b.user.v1.UpdateUserResponse\x12E\n" +
	"\n" +
	"DeleteUser\x12\x1a.user.v1.DeleteUserRequest\x1a\x1b.user.v1.DeleteUserResponse\x12B\n" +
	"\tListUsers\x12\x19.user.v1.ListUsersRequest\x1a\x1a.user.v1.ListUsersResponse\x12f\n" +
	"\x15GetUserPhotoUploadUrl\x12%.user.v1.GetUserPhotoUploadUrlRequest\x1a&.user.v1.GetUserPhotoUploadUrlResponse\x12i\n" +
	"\x16ConfirmUserPhotoUpload\x12&.user.v1.ConfirmUserPhotoUploadRequest\x1a'.user.v1.ConfirmUserPhotoUploadResponse\x12T\n" +
	"\x0fDeleteUserPhoto\x12\x1f.user.v1.DeleteUserPhotoRequest\x1a .user.v1.DeleteUserPhotoResponse\x12l\n" +
	"\x17GetUserPhotoDownloadUrl\x12'.user.v1.GetUserPhotoDownloadUrlRequest\x1a(.user.v1.GetUserPhotoDownloadUrlResponseB4Z2github.com/S1FFFkA/user-mgz/pkg/api/user/v1;userv1b\x06proto3"

var (
	file_gRPC_service_proto_rawDescOnce sync.Once
	file_gRPC_service_proto_rawDescData []byte
)

func file_gRPC_service_proto_rawDescGZIP() []byte {
	file_gRPC_service_proto_rawDescOnce.Do(func() {
		file_gRPC_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gRPC_service_proto_rawDesc), len(file_gRPC_service_proto_rawDesc)))
	})
	return file_gRPC_service_proto_rawDescData
}

var file_gRPC_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gRPC_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_gRPC_service_proto_goTypes = []any{
	(Sex)(0),                                // 0: user.v1.Sex
	(PhotoType)(0),                          // 1: user.v1.PhotoType
	(*City)(nil),                            // 2: user.v1.City
	(*UserPhoto)(nil),                       // 3: user.v1.UserPhoto
	(*User)(nil),                            // 4: user.v1.User
	(*CreateUserRequest)(nil),               // 5: user.v1.CreateUserRequest
	(*NewUserPhoto)(nil),                    // 6: user.v1.NewUserPhoto
	(*CreateUserResponse)(nil),              // 7: user.v1.CreateUserResponse
	(*GetUserRequest)(nil),                  // 8: user.v1.GetUserRequest
	(*GetUserResponse)(nil),                 // 9: user.v1.GetUserResponse
	(*UpdateUserRequest)(nil),               // 10: user.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),              // 11: user.v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),               // 12: user.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),              // 13: user.v1.DeleteUserResponse
	(*ListUsersRequest)(nil),                // 14: user.v1.ListUsersRequest
	(*ListUsersResponse)(nil),               // 15: user.v1.ListUsersResponse
	(*GetUserPhotoUploadUrlRequest)(nil),    // 16: user.v1.GetUserPhotoUploadUrlRequest
	(*GetUserPhotoUploadUrlResponse)(nil),   // 17: user.v1.GetUserPhotoUploadUrlResponse
	(*ConfirmUserPhotoUploadRequest)(nil),   // 18: user.v1.ConfirmUserPhotoUploadRequest
	(*ConfirmUserPhotoUploadResponse)(nil),  // 19: user.v1.ConfirmUserPhotoUploadResponse
	(*DeleteUserPhotoRequest)(nil),          // 20: user.v1.DeleteUserPhotoRequest
	(*DeleteUserPhotoResponse)(nil),         // 21: user.v1.DeleteUserPhotoResponse
	(*GetUserPhotoDownloadUrlRequest)(nil),  // 22: user.v1.GetUserPhotoDownloadUrlRequest
	(*GetUserPhotoDownloadUrlResponse)(nil), // 23: user.v1.GetUserPhotoDownloadUrlResponse
	(*timestamppb.Timestamp)(nil),           // 24: google.protobuf.Timestamp
}
var file_gRPC_service_proto_depIdxs = []int32{
	0,  // 0: user.v1.User.sex:type_name -> user.v1.Sex
	2,  // 1: user.v1.User.city:type_name -> user.v1.City
	3,  // 2: user.v1.User.extra_photos:type_name -> user.v1.UserPhoto
	24, // 3: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	24, // 4: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: user.v1.CreateUserRequest.sex:type_name -> user.v1.Sex
	6,  // 6: user.v1.CreateUserRequest.extra_photos:type_name -> user.v1.NewUserPhoto
	4,  // 7: user.v1.CreateUserResponse.user:type_name -> user.v1.User
	4,  // 8: user.v1.GetUserResponse.user:type_name -> user.v1.User
	0,  // 9: user.v1.UpdateUserRequest.sex:type_name -> user.v1.Sex
	6,  // 10: user.v1.UpdateUserRequest.extra_photos:type_name -> user.v1.NewUserPhoto
	4,  // 11: user.v1.UpdateUserResponse.user:type_name -> user.v1.User
	4,  // 12: user.v1.ListUsersResponse.users:type_name -> user.v1.User
	1,  // 13: user.v1.GetUserPhotoUploadUrlRequest.photo_type:type_name -> user.v1.PhotoType
	1,  // 14: user.v1.ConfirmUserPhotoUploadRequest.photo_type:type_name -> user.v1.PhotoType
	4,  // 15: user.v1.ConfirmUserPhotoUploadResponse.user:type_name -> user.v1.User
	1,  // 16: user.v1.GetUserPhotoDownloadUrlRequest.photo_type:type_name -> user.v1.PhotoType
	5,  // 17: user.v1.UserService.CreateUser:input_type -> user.v1.CreateUserRequest
	8,  // 18: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	10, // 19: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	12, // 20: user.v1.UserService.DeleteUser:input_type -> user.v1.DeleteUserRequest
	14, // 21: user.v1.UserService.ListUsers:input_type -> user.v1.ListUsersRequest
	16, // 22: user.v1.UserService.GetUserPhotoUploadUrl:input_type -> user.v1.GetUserPhotoUploadUrlRequest
	18, // 23: user.v1.UserService.ConfirmUserPhotoUpload:input_type -> user.v1.ConfirmUserPhotoUploadRequest
	20, // 24: user.v1.UserService.DeleteUserPhoto:input_type -> user.v1.DeleteUserPhotoRequest
	22, // 25: user.v1.UserService.GetUserPhotoDownloadUrl:input_type -> user.v1.GetUserPhotoDownloadUrlRequest
	7,  // 26: user.v1.UserService.CreateUser:output_type -> user.v1.CreateUserResponse
	9,  // 27: user.v1.UserService.GetUser:output_type -> user.v1.GetUserResponse
	11, // 28: user.v1.UserService.UpdateUser:output_type -> user.v1.UpdateUserResponse
	13, // 29: user.v1.UserService.DeleteUser:output_type -> user.v1.DeleteUserResponse
	15, // 30: user.v1.UserService.ListUsers:output_type -> user.v1.ListUsersResponse
	17, // 31: user.v1.UserService.GetUserPhotoUploadUrl:output_type -> user.v1.GetUserPhotoUploadUrlResponse
	19, // 32: user.v1.UserService.ConfirmUserPhotoUpload:output_type -> user.v1.ConfirmUserPhotoUploadResponse
	21, // 33: user.v1.UserService.DeleteUserPhoto:output_type -> user.v1.DeleteUserPhotoResponse
	23, // 34: user.v1.UserService.GetUserPhotoDownloadUrl:output_type -> user.v1.GetUserPhotoDownloadUrlResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_gRPC_service_proto_init() }
func file_gRPC_service_proto_init() {
	if File_gRPC_service_proto != nil {
		return
	}
	file_gRPC_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gRPC_service_proto_rawDesc), len(file_gRPC_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_service_proto_goTypes,
		DependencyIndexes: file_gRPC_service_proto_depIdxs,
		EnumInfos:         file_gRPC_service_proto_enumTypes,
		MessageInfos:      file_gRPC_service_proto_msgTypes,
	}.Build()
	File_gRPC_service_proto = out.File
	file_gRPC_service_proto_goTypes = nil
	file_gRPC_service_proto_depIdxs = nil
}
