// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: user_mgz.proto

package userv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CreateUser_FullMethodName              = "/user.v1.UserService/CreateUser"
	UserService_GetUser_FullMethodName                 = "/user.v1.UserService/GetUser"
	UserService_UpdateUser_FullMethodName              = "/user.v1.UserService/UpdateUser"
	UserService_DeleteUser_FullMethodName              = "/user.v1.UserService/DeleteUser"
	UserService_ListUsers_FullMethodName               = "/user.v1.UserService/ListUsers"
	UserService_GetUserPhotoUploadUrl_FullMethodName   = "/user.v1.UserService/GetUserPhotoUploadUrl"
	UserService_ConfirmUserPhotoUpload_FullMethodName  = "/user.v1.UserService/ConfirmUserPhotoUpload"
	UserService_GetUserPhotoDownloadUrl_FullMethodName = "/user.v1.UserService/GetUserPhotoDownloadUrl"
	UserService_DeleteUserPhoto_FullMethodName         = "/user.v1.UserService/DeleteUserPhoto"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	GetUserPhotoUploadUrl(ctx context.Context, in *GetUserPhotoUploadUrlRequest, opts ...grpc.CallOption) (*GetUserPhotoUploadUrlResponse, error)
	ConfirmUserPhotoUpload(ctx context.Context, in *ConfirmUserPhotoUploadRequest, opts ...grpc.CallOption) (*ConfirmUserPhotoUploadResponse, error)
	GetUserPhotoDownloadUrl(ctx context.Context, in *GetUserPhotoDownloadUrlRequest, opts ...grpc.CallOption) (*GetUserPhotoDownloadUrlResponse, error)
	DeleteUserPhoto(ctx context.Context, in *DeleteUserPhotoRequest, opts ...grpc.CallOption) (*DeleteUserPhotoResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, UserService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, UserService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserPhotoUploadUrl(ctx context.Context, in *GetUserPhotoUploadUrlRequest, opts ...grpc.CallOption) (*GetUserPhotoUploadUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPhotoUploadUrlResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserPhotoUploadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ConfirmUserPhotoUpload(ctx context.Context, in *ConfirmUserPhotoUploadRequest, opts ...grpc.CallOption) (*ConfirmUserPhotoUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmUserPhotoUploadResponse)
	err := c.cc.Invoke(ctx, UserService_ConfirmUserPhotoUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserPhotoDownloadUrl(ctx context.Context, in *GetUserPhotoDownloadUrlRequest, opts ...grpc.CallOption) (*GetUserPhotoDownloadUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPhotoDownloadUrlResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserPhotoDownloadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUserPhoto(ctx context.Context, in *DeleteUserPhotoRequest, opts ...grpc.CallOption) (*DeleteUserPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserPhotoResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteUserPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	GetUserPhotoUploadUrl(context.Context, *GetUserPhotoUploadUrlRequest) (*GetUserPhotoUploadUrlResponse, error)
	ConfirmUserPhotoUpload(context.Context, *ConfirmUserPhotoUploadRequest) (*ConfirmUserPhotoUploadResponse, error)
	GetUserPhotoDownloadUrl(context.Context, *GetUserPhotoDownloadUrlRequest) (*GetUserPhotoDownloadUrlResponse, error)
	DeleteUserPhoto(context.Context, *DeleteUserPhotoRequest) (*DeleteUserPhotoResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedUserServiceServer) GetUserPhotoUploadUrl(context.Context, *GetUserPhotoUploadUrlRequest) (*GetUserPhotoUploadUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPhotoUploadUrl not implemented")
}
func (UnimplementedUserServiceServer) ConfirmUserPhotoUpload(context.Context, *ConfirmUserPhotoUploadRequest) (*ConfirmUserPhotoUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmUserPhotoUpload not implemented")
}
func (UnimplementedUserServiceServer) GetUserPhotoDownloadUrl(context.Context, *GetUserPhotoDownloadUrlRequest) (*GetUserPhotoDownloadUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPhotoDownloadUrl not implemented")
}
func (UnimplementedUserServiceServer) DeleteUserPhoto(context.Context, *DeleteUserPhotoRequest) (*DeleteUserPhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserPhoto not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserPhotoUploadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPhotoUploadUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserPhotoUploadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserPhotoUploadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserPhotoUploadUrl(ctx, req.(*GetUserPhotoUploadUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ConfirmUserPhotoUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmUserPhotoUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ConfirmUserPhotoUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ConfirmUserPhotoUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ConfirmUserPhotoUpload(ctx, req.(*ConfirmUserPhotoUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserPhotoDownloadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPhotoDownloadUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserPhotoDownloadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserPhotoDownloadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserPhotoDownloadUrl(ctx, req.(*GetUserPhotoDownloadUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUserPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUserPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUserPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUserPhoto(ctx, req.(*DeleteUserPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
		{
			MethodName: "GetUserPhotoUploadUrl",
			Handler:    _UserService_GetUserPhotoUploadUrl_Handler,
		},
		{
			MethodName: "ConfirmUserPhotoUpload",
			Handler:    _UserService_ConfirmUserPhotoUpload_Handler,
		},
		{
			MethodName: "GetUserPhotoDownloadUrl",
			Handler:    _UserService_GetUserPhotoDownloadUrl_Handler,
		},
		{
			MethodName: "DeleteUserPhoto",
			Handler:    _UserService_DeleteUserPhoto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_mgz.proto",
}

const (
	PushTokenService_RegisterPushToken_FullMethodName = "/user.v1.PushTokenService/RegisterPushToken"
	PushTokenService_RemovePushToken_FullMethodName   = "/user.v1.PushTokenService/RemovePushToken"
)

// PushTokenServiceClient is the client API for PushTokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushTokenServiceClient interface {
	RegisterPushToken(ctx context.Context, in *RegisterPushTokenRequest, opts ...grpc.CallOption) (*RegisterPushTokenResponse, error)
	RemovePushToken(ctx context.Context, in *RemovePushTokenRequest, opts ...grpc.CallOption) (*RemovePushTokenResponse, error)
}

type pushTokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushTokenServiceClient(cc grpc.ClientConnInterface) PushTokenServiceClient {
	return &pushTokenServiceClient{cc}
}

func (c *pushTokenServiceClient) RegisterPushToken(ctx context.Context, in *RegisterPushTokenRequest, opts ...grpc.CallOption) (*RegisterPushTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPushTokenResponse)
	err := c.cc.Invoke(ctx, PushTokenService_RegisterPushToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushTokenServiceClient) RemovePushToken(ctx context.Context, in *RemovePushTokenRequest, opts ...grpc.CallOption) (*RemovePushTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePushTokenResponse)
	err := c.cc.Invoke(ctx, PushTokenService_RemovePushToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushTokenServiceServer is the server API for PushTokenService service.
// All implementations must embed UnimplementedPushTokenServiceServer
// for forward compatibility.
type PushTokenServiceServer interface {
	RegisterPushToken(context.Context, *RegisterPushTokenRequest) (*RegisterPushTokenResponse, error)
	RemovePushToken(context.Context, *RemovePushTokenRequest) (*RemovePushTokenResponse, error)
	mustEmbedUnimplementedPushTokenServiceServer()
}

// UnimplementedPushTokenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushTokenServiceServer struct{}

func (UnimplementedPushTokenServiceServer) RegisterPushToken(context.Context, *RegisterPushTokenRequest) (*RegisterPushTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPushToken not implemented")
}
func (UnimplementedPushTokenServiceServer) RemovePushToken(context.Context, *RemovePushTokenRequest) (*RemovePushTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePushToken not implemented")
}
func (UnimplementedPushTokenServiceServer) mustEmbedUnimplementedPushTokenServiceServer() {}
func (UnimplementedPushTokenServiceServer) testEmbeddedByValue()                          {}

// UnsafePushTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushTokenServiceServer will
// result in compilation errors.
type UnsafePushTokenServiceServer interface {
	mustEmbedUnimplementedPushTokenServiceServer()
}

func RegisterPushTokenServiceServer(s grpc.ServiceRegistrar, srv PushTokenServiceServer) {
	// If the following call panics, it indicates UnimplementedPushTokenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushTokenService_ServiceDesc, srv)
}

func _PushTokenService_RegisterPushToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPushTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushTokenServiceServer).RegisterPushToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushTokenService_RegisterPushToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushTokenServiceServer).RegisterPushToken(ctx, req.(*RegisterPushTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushTokenService_RemovePushToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePushTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushTokenServiceServer).RemovePushToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushTokenService_RemovePushToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushTokenServiceServer).RemovePushToken(ctx, req.(*RemovePushTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PushTokenService_ServiceDesc is the grpc.ServiceDesc for PushTokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushTokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.PushTokenService",
	HandlerType: (*PushTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPushToken",
			Handler:    _PushTokenService_RegisterPushToken_Handler,
		},
		{
			MethodName: "RemovePushToken",
			Handler:    _PushTokenService_RemovePushToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_mgz.proto",
}
